changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - "breaking-change"
    - title: 💡 Features
      labels:
        - "enhancement"
    - title: 🐞 Fixes
      labels:
        - "bug"
    - title: 📦 Dependencies
      labels: 
        - "dependencies"
    - title: 📖 Documentation
      labels:
        - "documentation"
    - title: 🛠 Others
      labels:
        - "*"
