changelog:
  categories:
    - title: :boom: Breaking Changes
      labels:
        - "breaking-change"
    - title: :bulb: Features
      labels:
        - "enhancement"
    - title: :lady_beetle: Fixes
      labels:
        - "bug"
    - title: :package: Dependencies
      labels: 
        - "dependencies"
    - title: :book: Documentation
      labels:
        - "documentation"
    - title: :hammer_and_wrench: Others
      labels:
        - "*"
