language: csharp
mono: none
dotnet: 2.1
install:
- dotnet restore
script:
- dotnet build
- dotnet test ./test/Ayaka.Tests/Ayaka.Tests.csproj
- dotnet test ./test/Ayaka.EntityFramework.Tests/Ayaka.EntityFramework.Tests.csproj