name: after-release

on:
  release:
    types: [ published ]

env:
  NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'

jobs:
  after-release:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    steps:
      - name: Use GitHub App
        uses: actions/create-github-app-token@67e27a7eb7db372a1c61a7f9bdab8699e9ee57f7 # v1
        id: app
        with:
          app-id: ${{ vars.AYAKA_RELEASES_APP_ID }}
          private-key: ${{ secrets.AYAKA_RELEASES_PRIVATE_KEY }}

      - name: Calculate Git User
        id: git-config
        run: |
          # Read the user info for the app, e.g. /users/renovate[bot]
          userId=$(gh api "/users/${{ steps.app.outputs.app-slug }}[bot]" --jq .id)

          echo "email=$userId+${{ steps.app.outputs.app-slug }}[bot]@users.noreply.github.com" >> "$GITHUB_OUTPUT"
          echo "name=${{ steps.app.outputs.app-slug }}[bot]" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ steps.app.outputs.token }}

      - name: NuGet Cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        with:
          path: |
            ${{ env.NUGET_PACKAGES }}
            .nuke/temp
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/global.json', '**/*.csproj', '**/*.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4

      - name: Restore .NET Tools
        run: |
          dotnet tool restore

      - name: Publish After-Release Changes
        run: |
          dotnet nuke AfterRelease \
            --github-token $GITHUB_TOKEN \
            --git-user-email $GIT_CONFIG_EMAIL \
            --git-user-name $GIT_CONFIG_NAME
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
          GIT_CONFIG_EMAIL: ${{ steps.git-config.outputs.email }}
          GIT_CONFIG_NAME: ${{ steps.git-config.outputs.name }}
