name: after-release

on:
  release:
    types: [ published ]

env:
  NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'

jobs:
  after-release:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    steps:
      - name: Use GitHub App
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        id: app
        with:
          app-id: ${{ vars.AYAKA_RELEASES_APP_ID }}
          private-key: ${{ secrets.AYAKA_RELEASES_PRIVATE_KEY }}

      - name: Calculate Git User
        id: git-config
        run: |
          # Read the user info for the app, e.g. /users/renovate[bot]
          userId=$(gh api "/users/${{ steps.app.outputs.app-slug }}[bot]" --jq .id)

          echo "email=$userId+${{ steps.app.outputs.app-slug }}[bot]@users.noreply.github.com" >> "$GITHUB_OUTPUT"
          echo "name=${{ steps.app.outputs.app-slug }}[bot]" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
          token: ${{ steps.app.outputs.token }}

      - name: NuGet Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ${{ env.NUGET_PACKAGES }}
            .nuke/temp
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/global.json', '**/*.csproj', '**/*.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4

      - name: Restore .NET Tools
        run: |
          dotnet tool restore

      - name: Publish After-Release Changes
        run: |
          dotnet nuke AfterRelease \
            --github-token $GITHUB_TOKEN \
            --git-user-email $GIT_CONFIG_EMAIL \
            --git-user-name $GIT_CONFIG_NAME
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
          GIT_CONFIG_EMAIL: ${{ steps.git-config.outputs.email }}
          GIT_CONFIG_NAME: ${{ steps.git-config.outputs.name }}
