name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: NuGet Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ${{ env.NUGET_PACKAGES }}
            .nuke/temp
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/global.json', '**/*.csproj', '**/*.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4

      - name: Restore .NET Tools
        run: |
          dotnet tool restore

      - name: Build, Test and Pack
        run: |
          dotnet nuke

      - name: Upload Coverage
        uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          directory: ${{ github.workspace }}/artifacts/coverage
          files: "*.cobertura.xml"

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ${{ github.workspace }}/artifacts/packages
          if-no-files-found: error

      - name: Publish NuGet packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet nuke Publish \
            --nuget-api-key $NUGET_API_KEY
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
