name: release

on:
  workflow_dispatch:

env:
  NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'

jobs:
  release:
      runs-on: ubuntu-latest

      concurrency:
        group: ${{ github.workflow }}
        cancel-in-progress: false

      steps:
        - name: Use GitHub App
          uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
          id: app
          with:          
            app-id: ${{ vars.AYAKA_RELEASES_APP_ID }}
            private-key: ${{ secrets.AYAKA_RELEASES_PRIVATE_KEY }}
          
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            fetch-depth: 0
            token: ${{ steps.app.outputs.token }}

        - name: NuGet Cache
          uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
          with:
            path: |
              ${{ env.NUGET_PACKAGES }}
              .nuke/temp
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/global.json', '**/*.csproj', '**/*.props') }}
            restore-keys: |
              ${{ runner.os }}-nuget-

        - name: Setup .NET
          uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4

        - name: Restore .NET Tools
          run: |
            dotnet tool restore

        - name: Create GitHub Release
          run: |
            dotnet nuke CreateRelease \
              --github-token $GITHUB_TOKEN
          env:
            GITHUB_TOKEN: ${{ steps.app.outputs.token }}
