name: release

on:
  workflow_dispatch:

env:
  NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'

jobs:
  release:
      runs-on: ubuntu-latest

      concurrency:
        group: ${{ github.workflow }}
        cancel-in-progress: false

      steps:
        - name: Use GitHub App
          uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1
          id: app
          with:          
            app-id: ${{ vars.AYAKA_RELEASES_APP_ID }}
            private-key: ${{ secrets.AYAKA_RELEASES_PRIVATE_KEY }}
          
        - name: Checkout
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
          with:
            fetch-depth: 0
            token: ${{ steps.app.outputs.token }}

        - name: NuGet Cache
          uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
          with:
            path: |
              ${{ env.NUGET_PACKAGES }}
              .nuke/temp
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/global.json', '**/*.csproj', '**/*.props') }}
            restore-keys: |
              ${{ runner.os }}-nuget-

        - name: Setup .NET
          uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4

        - name: Restore .NET Tools
          run: |
            dotnet tool restore

        - name: Create GitHub Release
          run: |
            dotnet nuke CreateRelease \
              --github-token $GITHUB_TOKEN
          env:
            GITHUB_TOKEN: ${{ steps.app.outputs.token }}
